schema_version = "1.0.0"

id = "Modifier_List_Fork"
version = "1.8.65"
name = "Modifier List [Fork]"
tagline = "Add-on to Enhanced UI layout for modifiers with handy features"
maintainer = "Antti Tikka, Draise, Dan-Gry"
type = "add-on"

website = "https://github.com/Dangry98/modifier_list-for-Blender-4.0"

tags = ["Modeling", "User Interface"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Save Add-on Prefrences"
